blog_chat_application/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blogs/", include('blogs.urls')),
    path("", include('chats.urls')),
    path("accounts/", include('accounts.urls')),
    path("tasks/", include('todotasks.urls')),
]

blogs/urls.py
from django.urls import path
from . import views as v

# blogs/ urls.
urlpatterns = [
    path("", v.blog_home, name="blog_home"),
    path("create-blog", v.blog_create, name="blog_create"),
    path("create-save", v.blog_saving, name="save_blog"),
]

chats/urls.py
from django.urls import path
from . import views as v

urlpatterns = [
    path("", v.home, name="home"),
    path('room/<str:pk>/',v.room,name='room'),
    path('create-room/',v.create_room,name='create-room'),
    path('update-room/<str:pk>/',v.update_room,name='update-room'),
    path('delete-room/<str:pk>/',v.delete,name='delete-room'),
    path('profile/<str:pk>/',v.profile,name="profile"),
    path('delete-message/<str:pk>/',v.deleteMessage,name='delete-message'),
    path('update-message/<str:pk>/',v.editMessage,name='update-message'),
]

chats/models.py
from django.db import models
from accounts.models import blogchatUser

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name

# room field defining
class Room(models.Model):
    host = models.ForeignKey(blogchatUser,on_delete=models.SET_NULL,null=True)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=200)
    desc = models.TextField(null=True,blank=True)
    # many rooms can have many participants i.e. users
    participants = models.ManyToManyField(blogchatUser,related_name="participants",blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    # defines the way in templating or the order will be returned
    class Meta:
        ordering = ['-updated','-created']

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    # custom user model
    # user can have many mesages (one to many relationship)
    user = models.ForeignKey(blogchatUser,on_delete=models.CASCADE)

    # on delete = models.SET_NULL means stay in db
    # on_delete = models.CASCADE means we delete every message in room
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.CharField(max_length=1000)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    # defines the way in templating or the order will be returned
    class Meta:
        ordering = ['-updated','-created']

    def __str__(self) -> str:
        return self.body[0:50]

chats/forms.py
from django.forms import ModelForm
from .models import Room,Message

# create class for the form
class roomform(ModelForm):
    class Meta:
        model = Room
        fields = ('topic','name','desc')

# for message editing
class messageEdit(ModelForm):
    class Meta:
        model = Message
        fields = ('body',)

chats/views.py
from django.shortcuts import render,redirect
# Create your views here.
from django.urls import path
from django.contrib import admin,messages
from django.http import HttpResponse
from django.db.models import Q
from .models import Room,Topic,Message
from .forms import roomform,messageEdit
from accounts.models import blogchatUser
from django.contrib.auth.decorators import login_required

def home(request):
    q = request.GET.get('q') if request.GET.get('q')!= None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains = q) |
        Q(desc__icontains = q)
        )
    room_count = rooms.count
    topics = Topic.objects.all()
    room_message = Message.objects.filter(
        Q(room__name__icontains = q) |
        Q(room__topic__name__icontains = q)
    )

    context ={'rooms':rooms,'topic':topics,'room_count':room_count,'room_message':room_message}
    return render(request,'chat_home.html',context)

# for user profile
def profile(request,pk):
    user = blogchatUser.objects.get(id=pk)
    rooms=user.room_set.all()
    topics = Topic.objects.all()
    room_message = user.message_set.all()
    context={'user':user,'rooms':rooms,'topic':topics,'room_message':room_message}
    return render(request,'profile/profile.html',context)

# for indivisual room
def room(request,pk):
    rooms = Room.objects.get(id=pk)
    # _set.all gives all the messages relate to this room
    comments= rooms.message_set.all().order_by('-created')

    # getting participants
    participants = rooms.participants.all()

    # adding comments in the room form
    if request.method == 'POST':
        newcomment = Message.objects.create(
            user = request.user,
            room = rooms,
            body = request.POST.get('body')
        )
        rooms.participants.add(request.user)
        rooms.save()
        return redirect('room',pk=rooms.id)

    context = {'rooms' : rooms, 'comments':comments,'participants':participants}
    return render(request,'base/room.html',context)

# Deleting the message
@login_required(login_url='/login')
def deleteMessage(request,pk):
    message = Message.objects.get(id=pk)

    if request.method == "POST":
        message.delete()
        return redirect('room',pk=message.room.id)
    return render(request,'base/delete.html',{'obj':message})

# editing the message
@login_required(login_url='/login')
def editMessage(request,pk):
    message = Message.objects.get(id=pk)
    form = messageEdit(instance=message)

    if (request.method =='POST'):
        form = messageEdit(request.POST,instance=message)
        if form.is_valid():
            form.save()
            return redirect('room',pk=message.room.id)

    context = {'form':form,'message':message}
    return render(request,'base/message_edit.html',context)

# Creating the room
@login_required(login_url='/login')
def create_room(request):
    form = roomform()
    topics = Topic.objects.all()
    if request.method =='POST':
        form = roomform(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.host = request.user
            room.save()
            room.participants.add(request.user)
            return redirect('home')

    context = {'form':form,'topics':topics}
    return render(request,'base/room_create.html',context)

# updating the room
@login_required(login_url='/login')
def update_room(request,pk):
    room = Room.objects.get(id=pk)
    topics = Topic.objects.all()
    form = roomform(instance=room)

    if request.user != room.host:
        return HttpResponse('You are not allowed to update this room')

    if (request.method =='POST'):
        form = roomform(request.POST,instance=room)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form':form,'room':room,'topics':topics}
    return render(request,'base/room_edit.html',context)

# delting the room
@login_required(login_url='/login')
def delete(request,pk):
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('You are not allowed to delete this room')

    if request.method == 'POST':
        room.delete()
        return redirect('home')
    return render(request, 'base/delete.html',context={'obj':room})

chats/templates/base/delete.html
{% extends 'main.html' %}
{% comment %} to delete any item from our project {% endcomment %}
{% block content %}
<div class="container my-4" style="height: 70vh;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card m-5">
                <div class="card-body px-3 py-4">
                    <form method="post" action="">
                        {% csrf_token %}
                        <p>Are you sure you want to delete <br> "{{obj}}"</p>
                        <input type='submit' value ='Confirm' class="btn btn-danger"/>
                        <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary">Go back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

chats/templates/base/message_edit.html
{% extends 'main.html' %}
{% comment %} to delete any item from our project {% endcomment %}
{% block content %}
<div class="container my-4" style="height: 70vh;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card m-5">
                <div class="card-body px-3 py-4">
                    <fieldset>
                        <legend>Update Message</legend>
                        <form action="" method="post">
                            {% csrf_token %}
                            <p class="form-group">
                                <label for="id_body" class="form-label">Body:</label>
                                <textarea name="body" cols="60" rows="4" required id="id_body" class="form-control">{{message.body}}</textarea>
                            </p>
                            <input type="submit" value="Submit" class=" btn btn-sm btn-primary form-control">
                        </form>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

chats/templates/base/recent_activity.html
{% if room_message %}
    {% for rm in room_message %}
        <div>
            <small><a href="{% url 'profile' rm.user.id %}">@{{ rm.user }}</a> -- {{rm.created|timesince}}</small>
            {% if request.user == rm.user %}
                <span style="margin-left: 3vh">
                    <a href="{% url 'update-message' rm.id%}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                    <a href="{% url 'delete-message' rm.id%}" class="mx-2 btn btn-sm btn-danger"><i class="fa fa-trash"></i></a>
                </span>
            {% endif %}
        </div>
        <br>
            <small>Replied in "{{rm.room}}"</small>
            <p>{{ rm }}</p>
            <hr>
    {% endfor %}
{% else %}
    <p>No Activity Found</p>
    <hr>
{% endif %}

chats/templates/base/room.html
{% extends 'main.html' %}

{% block content %}
<style>
    .room-wrapper{
        display:grid;
        grid-template-columns: 3fr 1fr;
        height: 76vh;
        margin: 5px;
    }
    .right-section{
        border: 0.5px solid;
        padding: 5px;
        border-radius: 5px;
        height: inherit;
        overflow-y: scroll;
    }
</style>
<div class="room-wrapper">
    <div>
        <div>
            <h3>{{rooms.name}}</h3>
        </div>
        <p>
            {{ rooms.desc }}
        </p>
        <hr/>
        <div class="comment-wrapper">
            <h4>CONVERSATION</h4>
            <hr>
            {% for com in comments %}
                <div class="comment" style="justify-content: space-between;">
                    <small><b>@{{com.user.username}}: {{com.created|timesince}}</b></small>

                    {% if request.user == com.user %}
                        <a href="{% url 'update-message' com.id %}" class="btn btn-primary btn-sm">Edit</a>
                        <a href="{% url 'delete-message' com.id%}" class="btn btn-primary btn-sm ">Delete</a>
                    {% endif %}
                    <p>{{com.body}}</p>
                    <hr>
                </div>
            {% endfor %}
        </div>
        <div class="comment-form">
            <form action="" method="post" class="container">
                {% csrf_token %}
                <textarea name="body" id="" cols="50" rows="3" class="form-control" placeholder="Write your message here"></textarea>
                <br>
                {% if request.user.is_authenticated %}
                    <input type="submit" value="Comment" class="btn btn-primary form-control">
                {% else %}
                    <a href="{% url 'loginpage' %}" class="btn" style="text-decoration:none;">
                        Comment
                    </a>
                {% endif %}
            </form>
        </div>
        <hr>
    </div>
        <div class="right-section">
            <h3>Participants</h3>
            <hr>
            {% for p in participants %}
              <p>@{{ p }}</p>
              <hr>
            {% endfor %}
        </div>
</div>

{% endblock %}

chats/templates/base/room_create.html
{% extends 'main.html' %}
{% block content %}
{% comment %} update and create rooms {% endcomment %}
    <fieldset style="height: 78vh;">
        <legend><a href="{% url 'create-room' %}" class="text-dark m-1">Create a room</a></legend>
        <form action="" method="post" class="mx-4">
            {% csrf_token %}
            <p class="form-group">
                <label for="id_topic" class="form-label">Topic:</label>
                <select name="topic" required id="id_topic" class="form-control">
                    <option value="" selected>---------</option>
                    {% for topic in topics %}
                        <option value="{{ topic.id }}">{{ topic.name }}</option>
                    {% endfor %}
                </select>
            </p>
            <p class="form-group">
                <label for="id_name" class="form-label">Name:</label>
                <input type="text" name="name" maxlength="200" required id="id_name" class="form-control">
            </p>
            <p>
                <label for="id_desc">Description:</label>
                <textarea name="desc" cols="60" rows="4" id="id_desc" class="form-control"></textarea>
            </p>
            <input type="submit" value="Submit" class=" btn btn-primary form-control">

        </form>
    </fieldset>
{% endblock content %}

chats/templates/base/room_edit.html
{% extends 'main.html' %}
{% block content %}
<fieldset style="height: 78vh;">
    <legend>Update room</legend>
    <form action="" method="post" class="mx-4">
        {% csrf_token %}
        <p class="form-group">
            <label for="id_topic" class="form-label">Topic:</label>
            <select name="topic" required="" id="id_topic" class="form-control">
                <option value="">---------</option>
                {% for topic in topics %}
                    <option value="{{ topic.id }}" {% if topic.id == room.topic.id %} selected {% endif %}>{{ topic.name }}</option>
                {% endfor %}
            </select>
        </p>
        <p class="form-group">
            <label for="id_name" class="form-label">Name:</label>
            <input type="text" name="name" value="{{ room.name }}" maxlength="200" required="" id="id_name" class="form-control">
        </p>
        <p class="form-group">
            <label for="id_desc" class="form-label">Description:</label>
            <textarea name="desc" cols="60" rows="4" id="id_desc" class="form-control">{{ room.desc }}</textarea>
        </p>
        <input type="submit" value="Submit" class=" btn btn-primary form-control">
    </form>
</fieldset>
{% endblock content %}

chats/templates/base/room_form.html
{% extends 'main.html' %}
{% block content %}
{% comment %} update and create rooms {% endcomment %}
    <fieldset>
        <legend><a href="{% url 'create-room' %}">Creating room</a></legend>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
        </form>
    </fieldset>
{% endblock content %}